[build]
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"

[[edge_functions]]
  path = "/api/db"
  function = "db"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
